env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
settings: { 'jest': { 'version': 27 } }
